### ISSUE TITLE
Upgrade to 1.27.4

### ISSUE THREAD

**Issue by rjackson** [tfwiki/mediawiki#12]
We're currently on 1.26.2, and the latest release supported by MediaWiki is their LTS 1.27.4 release.

[1.27 Release notes](https://www.mediawiki.org/wiki/Release_notes/1.27)

Rough upgrade process:
* Review release notes & evaluate changes
* Update code
* * Update Dockerfile to build atop [`mediawiki:lts`](https://github.com/wikimedia/mediawiki-docker/blob/d254f8c01cd0bbbed38bc0c71d0d70066d6fbbb4/lts/Dockerfile)
* * * This includes an upgrade to PHP 7, so also re-evaluate PHP extensions
* * Update extensions to relevant MediaWiki 1.27 release (hoping most will have a `REL1_27` branch)
* * Review breaking changes, and update our `LocalSettings.php` accordingly (the only first-party code)
* * Review [`scripts/itemredirect.php`](https://github.com/tfwiki/mediawiki/blob/8ff3d0ff601993a2968388a59c7e5b1f1c204f84/src/scripts/itemredirect.php#L1) and update for PHP 7, if necessary
* Spin up a dedicated test environment:
* * Clone database
* * Clone media disk
* * Dedicated stack running in isolated namespace
* Test upgrade
* * Deploy 1.27.4 to test stack
* * Upgrade database (spin up a dedicated job; release notes warn this could be a multi-hour process on a large wiki)
* * Review front-end & JS errors (we're already getting lots of warnings re: use of deprecated front-end via our `MediaWiki:Common.{css,js}`)
* * Test functionality
* * Fix unknowns & repeat step
* Deploy upgrade
* * Set MediaWiki to read-only (may not be necessary, but better to be safe)
* * Run database upgrade job
* * Deploy updated MediaWiki containers
* * Unset read only
* * Rejoice

## Configuration needing updates

[1.27 Configuration changes](https://www.mediawiki.org/wiki/Release_notes/1.27#Configuration_changes)

Config | Our value | Migration notes | Migration required?
--- | --- | --- | ---
`$wgScriptExtension` | `.php` | Deprecated. No migration needed for `.php`, just remove it. | ✅ Remove
`$wgArticlePath` | `/wiki/$1` | "`$wgArticlePath` must now be either a full url, or start with a "/"." | ❌ 
`$wgSessionsInObjectCache` | `true` | "Massive overhaul to session handling: ... "; 1.27 functionality equivalent to always being `true` | ✅ Remove

## Extension compatibility

Extension | Current version | 1.27 compatible version | Breaking changes?
--- | --- | --- | ---
[AbuseFilter](https://www.mediawiki.org/wiki/Extension:AbuseFilter)			| `REL1_23` | `REL1_27` |
[CategoryTree](https://www.mediawiki.org/wiki/Extension:CategoryTree)		| `REL1_22` | `REL1_27` |
[CodeEditor](https://www.mediawiki.org/wiki/Extension:CodeEditor)			| `REL1_22` | `REL1_27` |
[Echo](https://www.mediawiki.org/wiki/Extension:Echo)						| `REL1_26` | `REL1_27` |
[EmbedVideo](https://www.mediawiki.org/wiki/Extension:EmbedVideo)			| Very old ([64f7f457a553b849af684e2ad98df97ccf87ac8d](https://github.com/HydraWiki/mediawiki-embedvideo/commit/64f7f457a553b849af684e2ad98df97ccf87ac8d)) | 2.7.0 | 🤷‍♂️ Best give it a go
[GeeQuBox](https://www.mediawiki.org/wiki/Extension:GeeQuBox)				| `master` | `master` | 
[NewUserMessage](https://www.mediawiki.org/wiki/Extension:NewUserMessage)	| `REL1_23` | `REL1_27`
[RedditThumbnail](https://github.com/ThePortalWiki/RedditThumbnail)			| `master` | `master`
[RevQuery](https://github.com/ThePortalWiki/RevQuery)						| `master` | Uninstall, no longer required
[Scribunto](https://www.mediawiki.org/wiki/Extension:Scribunto)				| `REL1_21` | `REL1_27`
[Sentry](https://www.mediawiki.org/wiki/Extension:Sentry)					| `REL1_26` | `REL1_27`
[UserMerge](https://www.mediawiki.org/wiki/Extension:UserMerge)				| `REL1_21` | `REL1_27`

## Front-end issues

https://www.mediawiki.org/wiki/Manual:Interface/JavaScript#mw.config

[Fixed separately on-wiki](https://wiki.teamfortress.com/w/index.php?title=MediaWiki:Common.js&diff=prev&oldid=2315236)

## Task list

* [x] Review & evaluate release notes (see above)
* [x] Review extensions' compatibility (see above)
* [x] Updates to TF Wiki (config & extensions) (#13)
* [x] Testing:
* * [x] AbuseFilter
* * [x] CategoryTree
* * [x] CodeEditor
* * [x] Echo
* * [x] EmbedVideo
* * [x] GeeQuBox
* * [x] NewUserMessage
* * [x] RedditThumbnail
* * [x] Scribunto
* * [x] Sentry
* * [x] UserMerge
* [x] Production deployment
* [ ] Ongoing monitoring

**Comment by rjackson** [comment]
Tested & deployed to production. Will keep an eye on things through monitoring. 😉
